import os

DEBUG = True

USERNAME = ''
PASSWORD = ''
SERVER = ''
DB = ''

# SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_DATABASE_URI = ''

# SQLALCHEMY_TRACK_MODIFICATIONS = True

# SECRET_KEY = 'aplicacao_flask'
