"""empty message

Revision ID: f471df937676
Revises: 
Create Date: 2023-12-14 10:07:04.708349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f471df937676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('pontos', sa.String(length=2), nullable=False),
    sa.Column('jogos', sa.String(length=2), nullable=False),
    sa.Column('vitorias', sa.String(length=2), nullable=False),
    sa.Column('empates', sa.String(length=2), nullable=False),
    sa.Column('derrotas', sa.String(length=2), nullable=False),
    sa.Column('gols_pro', sa.String(length=2), nullable=False),
    sa.Column('gols_contra', sa.String(length=2), nullable=False),
    sa.Column('saldo_gols', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('posicao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time')
    # ### end Alembic commands ###
